### PR TITLE
Experimental switch to Google docs

### PR DESCRIPTION
**Pull request by drphilmarshall**
I am trying to modify the Makefile so that it downloads PDF from the Google doc draft instead of building it from latex. I think the Makefile is only triggered by a PR, so I am starting this now as part of the experiment, and will report back on how it goes. When he has been added to the lsst organization I'll add Steve M as reviewer, so that he can follow along. If this works, we could think of turning our Google doc draft into a Rubin-formatted technote document and using this repo to display the PDF technote at https://rtn-033.lsst.io/ Let's see!

### CODE REVIEW

**Comment by drphilmarshall** [comment]
Success! The Google doc PDF is now visible at https://rtn-033.lsst.io/v/feature-drphilmarshall-gdocs/index.html (and will appear at rtn-033.lsst.io when we merge this pull request). Now to discuss with Steve M offline whether or not to keep the source in Google docs, or make the jump to latex. If the latter, we would not merge this PR.

**Comment by drphilmarshall** [comment]
OK, the Makefile now points to the new, Rubin-formatted and Rubin-owned Google doc source, and I updated the README to point to it. @SteveMargheim I think you can merge this PR when you have reviewed the changes and are happy with them - and then you can announce your initial draft via a new PR when you have filled out all the text in the new doc. (We need a new PR to make the PDF at  https://rtn-033.lsst.io be a download of the current version in Google docs.)

**Comment by drphilmarshall** [comment]
PS. Note that to make a new PR, you have to edit one of the files in this GitHub repo. The thing to edit is the "Status" subsection of the README.

**Comment by timj** [comment]
As a general comment, if we are going down this route, it would be good to have an editable version of the document stored somewhere outside of google in case the google doc goes away and we are left with a PDF to extract text from. I assume you can pull such a file? I have no idea if an action can itself make a commit.

**Comment by drphilmarshall** [comment]
@timj That's a good idea. I've executed git commands from travis yaml in the past, but haven't tried anything like this with GitHub actions yet. I'll see what I can do. Downloading plain text from Google docs is straightforward.

**Comment by drphilmarshall** [comment]
Check it out, @timj - GitHub actions is now committing a new version of the plain text source to the repo just before it pushes the corresponding PDF, see screenshot below. (The git commit that GitHub actions makes does not, you'll be pleased to hear, itself trigger a new GitHub action - as you can see in the commit history above.) This was a good addition I think - thanks for suggesting it.

image

**Comment by drphilmarshall** [comment]
OK @SteveMargheim I think this is good to go. LMK if you see anything else that needs fixing!

**Pull request merged**
